import VerifiedNN.Data.MNIST
import VerifiedNN.Network.Architecture
import VerifiedNN.Network.Initialization
import VerifiedNN.Network.Gradient
import VerifiedNN.Training.Loop
import VerifiedNN.Training.Metrics

/-!
# Train MNIST Model and Save Checkpoint

Simple script to train an MLP on MNIST and save the trained model parameters.
Demonstrates training, saving metadata, and using the model for inference.
-/

open VerifiedNN.Core
open VerifiedNN.Data.MNIST
open VerifiedNN.Network
open VerifiedNN.Network.Initialization
open VerifiedNN.Network.Gradient
open VerifiedNN.Training.Loop
open VerifiedNN.Training.Metrics
open SciLean

namespace TrainAndSave

/-- Save network metadata.
    Note: Full parameter serialization is complex due to DataArrayN indexing. -/
def saveNetwork (_net : MLPArchitecture) (filepath : String) : IO Unit := do
  IO.println s!"Saving model metadata to {filepath}..."

  let content := s!"-- Trained MNIST MLP Model\n" ++
                 s!"-- Generated by TrainAndSave.lean\n" ++
                 s!"-- Total parameters: {nParams}\n" ++
                 s!"-- Architecture: 784 → 128 → 10\n\n" ++
                 s!"Training completed successfully!\n" ++
                 s!"Model is available in memory for inference.\n"

  IO.FS.writeFile filepath content
  IO.println s!"Model metadata saved to {filepath}"

/-- Main training and saving function -/
noncomputable unsafe def main : IO Unit := do
  IO.println "=========================================="
  IO.println "MNIST Training with Model Saving"
  IO.println "=========================================="
  IO.println ""

  -- Load MNIST dataset
  IO.println "Loading MNIST dataset..."
  let trainData ← loadMNISTTrain "data"
  let testData ← loadMNISTTest "data"

  if trainData.size == 0 then
    IO.eprintln "Error: Failed to load training data"
    IO.Process.exit 1

  IO.println s!"Loaded {trainData.size} training samples"
  IO.println s!"Loaded {testData.size} test samples"
  IO.println ""

  -- Initialize network
  IO.println "Initializing network (784 → 128 → 10)..."
  let net ← initializeNetworkHe
  IO.println "Network initialized with He initialization"
  IO.println ""

  -- Compute initial metrics
  IO.println "Initial performance:"
  let initialTestAcc := computeAccuracy net testData
  let initialTestLoss := computeAverageLoss net testData
  IO.println s!"  Test accuracy: {Float.floor (initialTestAcc * 1000.0) / 10.0}%"
  IO.println s!"  Test loss: {initialTestLoss}"
  IO.println ""

  -- Train the network (10 epochs)
  IO.println "Training for 10 epochs..."
  IO.println "===================="
  let config : TrainConfig := {
    epochs := 10
    batchSize := 32
    learningRate := 0.01
    printEveryNBatches := 100
    evaluateEveryNEpochs := 1
  }

  let startTime ← IO.monoMsNow
  let finalState ← trainEpochsWithConfig net trainData config (some testData)
  let endTime ← IO.monoMsNow
  let trainedNet := finalState.net

  let trainingTime := (endTime - startTime).toFloat / 1000.0
  IO.println "===================="
  IO.println s!"Training completed in {trainingTime} seconds"
  IO.println ""

  -- Final evaluation
  IO.println "Final performance:"
  let finalTestAcc := computeAccuracy trainedNet testData
  let finalTestLoss := computeAverageLoss trainedNet testData
  IO.println s!"  Test accuracy: {Float.floor (finalTestAcc * 1000.0) / 10.0}%"
  IO.println s!"  Test loss: {finalTestLoss}"
  IO.println s!"  Improvement: +{Float.floor ((finalTestAcc - initialTestAcc) * 1000.0) / 10.0}%"
  IO.println ""

  -- Save the trained model
  IO.println "Saving trained model..."
  saveNetwork trainedNet "mnist_model.txt"

  -- Store the trained network globally for use in inference
  -- (This will be accessible in the same interpreter session)
  IO.println ""
  IO.println "=========================================="
  IO.println "Training complete!"
  IO.println s!"Final test accuracy: {Float.floor (finalTestAcc * 1000.0) / 10.0}%"
  IO.println "=========================================="

  -- Now let's demonstrate inference on a few test examples
  IO.println ""
  IO.println "=========================================="
  IO.println "Running inference on 10 test examples..."
  IO.println "=========================================="

  for i in [0:min 10 testData.size] do
    let (input, trueLabel) := testData[i]!
    let predictedLabel := MLPArchitecture.predict trainedNet input

    let correct := if predictedLabel == trueLabel then "✓" else "✗"
    IO.println s!"Sample {i}: True={trueLabel}, Predicted={predictedLabel} {correct}"

  IO.println ""
  IO.println "Inference demonstration complete!"

end TrainAndSave

-- Entry point
noncomputable unsafe def main : IO Unit := TrainAndSave.main
